#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
#  Telegram Media Downloader Bot — One-shot installer
#  Repo: https://github.com/moha100x/botdownloderplus
#
#  Usage:
#    bash install.sh                              # interactive
#    BOT_TOKEN=xxx ADMIN_ID=123 bash install.sh   # non-interactive
#
#  Works on: Ubuntu 20.04+ / Debian 11+ (root or sudo).
#  Installs: Node.js 20, pnpm, ffmpeg, python3, yt-dlp deps,
#           clones the repo, writes .env, builds, and launches
#           a systemd service `tgdlbot` that auto-restarts.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_URL="https://github.com/moha100x/botdownloderplus.git"
INSTALL_DIR="${INSTALL_DIR:-/opt/botdownloderplus}"
SERVICE_NAME="tgdlbot"
NODE_MAJOR="20"

# ── helpers ──────────────────────────────────────────────────────────
GREEN=$'\e[32m'; CYAN=$'\e[36m'; YELLOW=$'\e[33m'; RED=$'\e[31m'; BOLD=$'\e[1m'; RESET=$'\e[0m'
ok()   { printf "%s✅ %s%s\n" "$GREEN" "$*" "$RESET"; }
info() { printf "%s➜  %s%s\n" "$CYAN" "$*" "$RESET"; }
warn() { printf "%s⚠️  %s%s\n" "$YELLOW" "$*" "$RESET"; }
die()  { printf "%s❌ %s%s\n" "$RED" "$*" "$RESET" >&2; exit 1; }
hdr()  { printf "\n%s%s── %s ──%s\n" "$BOLD" "$CYAN" "$*" "$RESET"; }

SUDO=""
if [[ $EUID -ne 0 ]]; then
  command -v sudo >/dev/null || die "این اسکریپت نیاز به root یا sudo دارد."
  SUDO="sudo"
fi

# ── 1. validate inputs ───────────────────────────────────────────────
hdr "گام ۱: دریافت توکن و آیدی ادمین"

if [[ -z "${BOT_TOKEN:-}" ]]; then
  read -rp "${BOLD}توکن بات تلگرام (از @BotFather): ${RESET}" BOT_TOKEN
fi
[[ "$BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]{30,}$ ]] || die "فرمت BOT_TOKEN نامعتبر است."

if [[ -z "${ADMIN_ID:-}" ]]; then
  read -rp "${BOLD}آیدی عددی ادمین (از @userinfobot): ${RESET}" ADMIN_ID
fi
[[ "$ADMIN_ID" =~ ^[0-9]+$ ]] || die "ADMIN_ID باید فقط عدد باشد."

info "اعتبارسنجی توکن با Telegram API ..."
RESP="$(curl -fsSL --max-time 15 "https://api.telegram.org/bot${BOT_TOKEN}/getMe" || true)"
echo "$RESP" | grep -q '"ok":true' || die "توکن نامعتبر است یا اتصال اینترنت مشکل دارد."
BOT_USERNAME="$(echo "$RESP" | sed -n 's/.*"username":"\([^"]*\)".*/\1/p')"
ok "متصل شد به: @${BOT_USERNAME}"

# ── 2. system dependencies ──────────────────────────────────────────
hdr "گام ۲: نصب پکیج‌های سیستمی"
export DEBIAN_FRONTEND=noninteractive
$SUDO apt-get update -y
$SUDO apt-get install -y curl ca-certificates git python3 python3-pip ffmpeg build-essential
ok "ابزارهای پایه نصب شد"

# ── 3. Node.js ──────────────────────────────────────────────────────
if ! command -v node >/dev/null || [[ "$(node -v | sed 's/v\([0-9]*\).*/\1/')" -lt "$NODE_MAJOR" ]]; then
  info "نصب Node.js ${NODE_MAJOR}.x ..."
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | $SUDO -E bash -
  $SUDO apt-get install -y nodejs
fi
ok "Node.js: $(node -v)"

# ── 4. pnpm ─────────────────────────────────────────────────────────
if ! command -v pnpm >/dev/null; then
  info "نصب pnpm ..."
  $SUDO npm install -g pnpm
fi
ok "pnpm: $(pnpm -v)"

# ── 5. clone / update repo ──────────────────────────────────────────
hdr "گام ۳: دریافت سورس کد"
$SUDO mkdir -p "$(dirname "$INSTALL_DIR")"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "ریپو موجود است — بروزرسانی ..."
  $SUDO git -C "$INSTALL_DIR" fetch --all --prune
  $SUDO git -C "$INSTALL_DIR" reset --hard origin/HEAD
else
  $SUDO git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi
$SUDO chown -R "$USER":"$USER" "$INSTALL_DIR"
ok "سورس آماده در: $INSTALL_DIR"

# ── 6. write .env ───────────────────────────────────────────────────
hdr "گام ۴: نوشتن فایل پیکربندی"
ENV_FILE="$INSTALL_DIR/artifacts/telegram-bot/.env"
cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
BOT_TOKEN=${BOT_TOKEN}
ADMIN_ID=${ADMIN_ID}
DOWNLOAD_DIR=./downloads
MAX_FILE_SIZE_MB=50
RATE_LIMIT_REQUESTS=5
RATE_LIMIT_WINDOW_MS=60000
LOG_LEVEL=info
EOF
chmod 600 "$ENV_FILE"
ok ".env نوشته شد"

# ── 7. install deps & build ─────────────────────────────────────────
hdr "گام ۵: نصب وابستگی‌ها و build"
cd "$INSTALL_DIR"
pnpm install --frozen-lockfile || pnpm install
pnpm --filter @workspace/telegram-bot run build
ok "بات build شد"

# ── 8. systemd service ──────────────────────────────────────────────
hdr "گام ۶: ساخت سرویس systemd"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
$SUDO tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=Telegram Media Downloader Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${USER}
WorkingDirectory=${INSTALL_DIR}/artifacts/telegram-bot
Environment=NODE_ENV=production
ExecStart=$(command -v node) ${INSTALL_DIR}/artifacts/telegram-bot/dist/index.cjs
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

$SUDO systemctl daemon-reload
$SUDO systemctl enable "$SERVICE_NAME"
$SUDO systemctl restart "$SERVICE_NAME"
sleep 2
$SUDO systemctl --no-pager --full status "$SERVICE_NAME" | head -n 12 || true

ok "سرویس $SERVICE_NAME راه‌اندازی شد"

# ── 9. summary ──────────────────────────────────────────────────────
hdr "پایان نصب 🎉"
cat <<EOF

${BOLD}اطلاعات بات:${RESET}
  • نام کاربری : @${BOT_USERNAME}
  • آیدی ادمین : ${ADMIN_ID}
  • مسیر نصب  : ${INSTALL_DIR}
  • سرویس     : ${SERVICE_NAME}

${BOLD}دستورات مفید:${RESET}
  مشاهده لاگ زنده :   sudo journalctl -u ${SERVICE_NAME} -f
  ری‌استارت سرویس :   sudo systemctl restart ${SERVICE_NAME}
  توقف سرویس     :   sudo systemctl stop ${SERVICE_NAME}
  وضعیت          :   sudo systemctl status ${SERVICE_NAME}
  ویرایش .env    :   nano ${ENV_FILE} && sudo systemctl restart ${SERVICE_NAME}

حالا در تلگرام به @${BOT_USERNAME} پیام /start بدهید.
EOF
