#!/usr/bin/env node
/**
 * Interactive Setup Script for Telegram Media Downloader Bot
 * Run: node setup.mjs
 */

import readline from "readline/promises";
import { stdin as input, stdout as output } from "process";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = resolve(__dirname, ".env");

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const GREEN = "\x1b[32m";
const CYAN = "\x1b[36m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const DIM = "\x1b[2m";

function print(msg) {
  console.log(msg);
}

function success(msg) {
  print(`${GREEN}✅ ${msg}${RESET}`);
}

function warn(msg) {
  print(`${YELLOW}⚠️  ${msg}${RESET}`);
}

function error(msg) {
  print(`${RED}❌ ${msg}${RESET}`);
}

function header(msg) {
  print(`\n${BOLD}${CYAN}${msg}${RESET}`);
}

function separator() {
  print(`${DIM}${"─".repeat(50)}${RESET}`);
}

async function validateBotToken(token) {
  const res = await fetch(`https://api.telegram.org/bot${token}/getMe`);
  const data = await res.json();
  if (!data.ok) throw new Error(data.description ?? "Invalid token");
  return data.result;
}

async function main() {
  console.clear();
  print(`${BOLD}${CYAN}`);
  print(`  ╔════════════════════════════════════════╗`);
  print(`  ║   🎵 Telegram Media Downloader Bot     ║`);
  print(`  ║        Setup & Configuration           ║`);
  print(`  ╚════════════════════════════════════════╝`);
  print(`${RESET}`);

  if (existsSync(ENV_PATH)) {
    warn(".env file already exists.");
    print(`${DIM}Continuing will overwrite your existing configuration.${RESET}\n`);
  }

  const rl = readline.createInterface({ input, output, terminal: true });

  try {
    header("Step 1: Telegram Bot Token");
    separator();
    print(`${DIM}Get your token from @BotFather on Telegram.${RESET}`);
    print(`${DIM}Command: /newbot → follow instructions → copy the token.${RESET}\n`);

    let botInfo;
    let botToken = "";

    while (!botInfo) {
      botToken = (await rl.question(`${BOLD}Enter Bot Token: ${RESET}`)).trim();
      if (!botToken) {
        error("Token cannot be empty.");
        continue;
      }
      if (!/^\d+:[A-Za-z0-9_-]{35,}$/.test(botToken)) {
        error("Invalid token format. Expected: 123456789:ABCdefGHI...");
        continue;
      }
      print(`\n${DIM}Validating token with Telegram API...${RESET}`);
      try {
        botInfo = await validateBotToken(botToken);
        success(`Connected to @${botInfo.username} (ID: ${botInfo.id})`);
      } catch (err) {
        error(`Token validation failed: ${err.message}`);
        botInfo = null;
      }
    }

    header("Step 2: Admin Telegram ID");
    separator();
    print(`${DIM}Your numeric Telegram user ID. Get it from @userinfobot.${RESET}\n`);

    let adminId = "";
    while (!adminId || isNaN(Number(adminId))) {
      adminId = (await rl.question(`${BOLD}Enter Admin Telegram ID: ${RESET}`)).trim();
      if (!adminId || isNaN(Number(adminId)) || Number(adminId) <= 0) {
        error("Please enter a valid numeric Telegram user ID.");
        adminId = "";
      }
    }

    header("Step 3: Advanced Settings");
    separator();
    print(`${DIM}Press Enter to keep the default value shown in brackets.${RESET}\n`);

    const downloadDir = (await rl.question(`Download directory [./downloads]: `)).trim() || "./downloads";
    const maxSizeStr = (await rl.question(`Max file size in MB [50]: `)).trim() || "50";
    const rateLimitStr = (await rl.question(`Max requests per minute per user [5]: `)).trim() || "5";

    const maxSize = Math.max(1, Math.min(2000, Number(maxSizeStr) || 50));
    const rateLimit = Math.max(1, Math.min(60, Number(rateLimitStr) || 5));

    header("Step 4: Writing Configuration");
    separator();

    const envContent = [
      `# Telegram Media Downloader Bot — Configuration`,
      `# Generated by setup.mjs on ${new Date().toISOString()}`,
      ``,
      `# ─── Required ─────────────────────────────────`,
      `BOT_TOKEN=${botToken}`,
      `ADMIN_ID=${adminId}`,
      ``,
      `# ─── Download Settings ──────────────────────────`,
      `DOWNLOAD_DIR=${downloadDir}`,
      `MAX_FILE_SIZE_MB=${maxSize}`,
      ``,
      `# ─── Rate Limiting ──────────────────────────────`,
      `RATE_LIMIT_REQUESTS=${rateLimit}`,
      `RATE_LIMIT_WINDOW_MS=60000`,
      ``,
      `# ─── Logging ─────────────────────────────────────`,
      `LOG_LEVEL=info`,
      ``,
    ].join("\n");

    writeFileSync(ENV_PATH, envContent, "utf8");
    success(".env file written successfully!");

    print(`\n${BOLD}${GREEN}`);
    print(`  ╔════════════════════════════════════════╗`);
    print(`  ║       Setup Complete! 🎉               ║`);
    print(`  ╚════════════════════════════════════════╝`);
    print(`${RESET}`);

    print(`\n${BOLD}Configuration Summary:${RESET}`);
    print(`  Bot:        @${botInfo.username}`);
    print(`  Admin ID:   ${adminId}`);
    print(`  Downloads:  ${downloadDir}`);
    print(`  Max Size:   ${maxSize} MB`);
    print(`  Rate Limit: ${rateLimit} req/min`);

    print(`\n${BOLD}${CYAN}To start the bot, run:${RESET}`);
    print(`  ${BOLD}pnpm --filter @workspace/telegram-bot run dev${RESET}`);
    print(`\n${DIM}Or in production:${RESET}`);
    print(`  ${BOLD}pnpm --filter @workspace/telegram-bot run start${RESET}\n`);
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  error(`Setup failed: ${err.message}`);
  process.exit(1);
});
